Feature encryption rekey
dell/csi-powerscale pull request #147
Opened 2022-11-11 15:47 UTC by alexemc

# Description
This change adds support of rekeying to Encryption. Encryption driver container now exposes an API endpoint used by the rekey CRD controller (installed separately).

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Tested that helm install was not affected by this change with and without Encryption enabled. Testing specific to the rekeying functionality is done in the scope of csm-encryption.

2022-11-11 16:31 UTC, sharmilarama approved these changes

2022-11-11 16:34 UTC, anathoodell submitted a review, later dismissed

2022-11-11 19:25 UTC, nitesh3108 approved these changes

2022-11-11 19:26 UTC, nitesh3108 requested changes
Pls sign your commits

2022-11-11 19:39 UTC, shefali-malhotra reviewed
Please do verify driver upgrade scenario if not done, with these changes. 
Also add the necessary UT cases.

2022-11-14 22:28 UTC, alexemc commented
> Pls sign your commits

Done. Merged, rebased and signed.

2022-11-14 22:30 UTC, alexemc commented
> Please do verify driver upgrade scenario if not done, with these changes. Also add the necessary UT cases.

Successfully tested upgrade from 2.4 to main with encryption disabled.
Successfully tested upgrade from 2.4 to main with encryption enabled.
No UT required for this change.

2022-11-15 00:22 UTC, anathoodell submitted a review, later dismissed

2022-11-15 05:27 UTC, bpjain2004 reviewed
The changes in this PR LGTM. I have one comment regarding encryption.imagePullPolicy param. We have a global/generic imagePullPolicy param applicable for all the sidecars. And this is consistent behavior across all the drivers. Unless really required I suggest removing encryption.imagePullPolicy param, either through this PR or a separate PR.

2022-11-15 13:37 UTC, alexemc commented
> The changes in this PR LGTM. I have one comment regarding encryption.imagePullPolicy param. We have a global/generic imagePullPolicy param applicable for all the sidecars. And this is consistent behavior across all the drivers. Unless really required I suggest removing encryption.imagePullPolicy param, either through this PR or a separate PR.

The default behavior is to use the global imagePullPolicy. encryption.imagePullPolicy, if specified, allows overriding the policy for encryption only. Extremely handy for testing.

2022-11-15 15:37 UTC, nitesh3108 approved these changes

2022-11-15 15:38 UTC, merged