Remove possible nil pointer dereference in mkdir
dell/csi-powerscale pull request #226
Opened 2023-10-23 13:54 UTC by cbartoszDell

# Description
There was a possibility for nil pointer dereference on `os.Stat` result. This is now fixed. Also refactored the function so there is less nesting and happy path is the default.

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
I have crated test cases for all but one path in the function, because I haven't found a way to trigger `fs` errors other than `fs.ErrNotFound` easily. The logic is pretty simple so it should be correct.

2023-10-31 09:52 UTC, nitesh3108 approved these changes

2023-10-31 10:21 UTC, chimanjain approved these changes

2023-10-31 13:21 UTC, gallacher requested changes
Is this a fix related to a GitHub bug? Or part of feature implementation? Please associate this PR with a GitHub issue.  Thanks.

2023-10-31 17:03 UTC, gallacher requested changes
Is this code change fixing a defect? Please associate it with a GitHub issue.  Thanks.

2023-11-07 17:31 UTC, gallacher approved these changes

2023-11-07 17:37 UTC, merged