Update offline bundle instructions from CSI to CSM Operator
dell/csi-powerscale pull request #235
Opened 2023-12-14 18:28 UTC by KerryKovacevic

# Description
Updated documentation for offline bundle installation from referencing CSI Operator to CSM Operator.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1081|

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2023-12-15 04:19 UTC, shanmydell requested changes
![image](https://github.com/dell/csi-powerscale/assets/82038610/3eeb1777-381c-4ae6-96fa-770695ae588d)
Need an update here

2023-12-18 19:48 UTC, mdutka-dell approved these changes

2023-12-19 14:52 UTC, PeresKereotubo approved these changes

2023-12-20 12:37 UTC, bharathsreekanth approved these changes

2023-12-20 13:01 UTC, shanmydell approved these changes

2023-12-21 12:12 UTC, nitesh3108 approved these changes

2023-12-21 12:14 UTC, chimanjain approved these changes

2023-12-21 12:14 UTC, merged