Added make target to build without cache
dell/csi-powerscale pull request #278
Opened 2024-09-03 16:04 UTC by francis-nijay

# Description
Image build job fails because of no space left on the build machine. This is caused by overlay images created during the build process

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1448 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Tested build and there are no overlay containers left mounted on the build machine

2024-09-03 16:04 UTC, francis-nijay commented
![image](https://github.com/user-attachments/assets/b5decc7a-1d4c-44b9-9677-1a5fdbe2eb62)
Overlay containers are not present after the build id completed

2024-09-03 17:34 UTC, alexemc requested changes

2024-09-03 17:34 UTC, alexemc commented on docker.mk
> +
I suggest removing the code duplication with something like this:

```
podman-build: download-csm-common
	$(eval include csm-common.mk)
	@echo "Base Image is set to: $(DEFAULT_BASEIMAGE)"
	@echo "Adding Driver dependencies to $(DEFAULT_BASEIMAGE)"
	bash ./buildubimicro.sh $(DEFAULT_BASEIMAGE)
	@echo "Base image build: SUCCESS" $(eval BASEIMAGE=localhost/csipowerscale-ubimicro:latest)
	@echo "Building: $(REGISTRY)/$(IMAGENAME):$(IMAGETAG)"
	@echo "Using Golang Image $(DEFAULT_GOIMAGE)"
	$(BUILDER) build $(NOCACHE) -t "$(REGISTRY)/$(IMAGENAME):$(IMAGETAG)" -f Dockerfile.podman --target $(BUILDSTAGE) --build-arg GOPROXY=$(GOPROXY) --build-arg BASEIMAGE=$(BASEIMAGE) --build-arg GOIMAGE=$(DEFAULT_GOIMAGE) .

podman-build-no-cache:
	@echo "Building with --no-cache ..."
	@make podman-build NOCACHE=--no-cache
```

2024-09-03 20:04 UTC, alexemc approved these changes

2024-09-03 20:29 UTC, donatwork approved these changes

2024-09-04 02:03 UTC, bpjain2004 approved these changes

2024-09-06 06:51 UTC, nitesh3108 approved these changes

2024-09-06 07:40 UTC, merged